name: Quadient Deployment
 
on:
  push:
    branches: [ main ]        # triggers on push
  workflow_dispatch:           # allows manual trigger from GitHub UI
 
jobs:
  deploy:
    runs-on: [self-hosted, FopDev]       # targets your local runner
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
 
      - name: Run PowerShell Export script
        shell: powershell
        run: |
          .\scripts\Export.ps1
