name: Quadient Staging Import
 
on:
  push:
    branches: [ main ]        # triggers on push
  workflow_dispatch:           # allows manual trigger from GitHub UI
 
jobs:
  deploy:
    runs-on: [self-hosted, dev1]       # targets your local runner
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
 
      - name: Run CMD snapshot script
        shell: cmd
        run: |
          scripts\snapshot.bat

      - name: Run PowerShell Import script
        shell: powershell
        run: |
          .\scripts\Import.ps1
